name: SBT CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPO_URL: registry.sgeorgi.io
      REPO_IMAGE: test-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Build and Test
        run: sbt -v +test

  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_URL: 927485958639.dkr.ecr.eu-central-1.amazonaws.com
      REPO_IMAGE: test-api-6dce598
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Docker image
        run: sbt -v +docker:publish
