name: SBT CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPO_URL: registry.sgeorgi.io
      REPO_IMAGE: test-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Build and Test
        run: sbt -v +test
        with:
          fail_ci_if_error: true
  containerize:
    runs-on: ubuntu-latest
    env:
      REPO_URL: registry.sgeorgi.io
      REPO_IMAGE: test-api
    steps:
    - uses: actions/checkout@v2
      name: Build docker image
      run: sbt docker:stage
      with:
        fail_ci_if_error: true
