name: SBT CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPO_URL: registry.sgeorgi.io
      REPO_IMAGE: test-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Build and Test
        run: sbt -v +test
